model_path = "models/colorization_release_v2.caffemodel"
pro_text_path = "models/models_colorization_deploy_v2.prototxt"
points_path = "models/pts_in_hull.npy"
input_path = "input"
output_path = "output"
